INSERT INTO Players (Name) VALUES ('РАФАЭЛЬ НАДАЛЬ');
INSERT INTO Players (Name) VALUES ('РОДЖЕР ФЕДЕРЕР');
INSERT INTO Players (Name) VALUES ('НОВАК ДЖОКОВИЧ');
INSERT INTO Players (Name) VALUES ('ДАНИИЛ МЕДВЕДЕВ');
INSERT INTO Players (Name) VALUES ('КАРЛОС АЛЬКАРАС');
INSERT INTO Players (Name) VALUES ('БЬОРН БОРГ');
INSERT INTO Players (Name) VALUES ('АНДРЕ АГАССИ');
INSERT INTO Players (Name) VALUES ('АНДРЕЙ РУБЛЁВ');
INSERT INTO Players (Name) VALUES ('ПИТ САМПРАС');
INSERT INTO Players (Name) VALUES ('ЭНДИ РОДДИК');
INSERT INTO Matches (Player1, Player2, Winner) VALUES (1, 2, 2);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (2, 3, 2);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (3, 4, 4);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (4, 5, 4);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (5, 6, 5);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (6, 7, 6);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (7, 8, 8);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (8, 9, 8);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (9, 10, 10);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (2, 9, 2);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (2, 7, 2);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (4, 9, 4);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (4, 8, 8);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (4, 6, 4);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (3, 4, 3);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (3, 5, 3);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (3, 7, 3);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (2, 7, 2);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (2, 5, 2);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (6, 2, 2);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (9, 3, 3);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (1, 3, 1);


