-- DROP TABLE IF EXISTS Players CASCADE;
-- DROP TABLE IF EXISTS Matches;
CREATE TABLE IF NOT EXISTS Players (ID int PRIMARY KEY AUTO_INCREMENT, Name varchar(30) NOT NULL);
CREATE TABLE IF NOT EXISTS Matches (ID int PRIMARY KEY AUTO_INCREMENT, Player1 int REFERENCES Players(ID), Player2 int REFERENCES Players(ID), Winner int REFERENCES Players(ID));